#!/usr/bin/env bash

python var1D.py --f1 nose_puidtiming_bdt_v2.root  --h1 signal_jets_time_moments_0 --l1 'VBF jets' --f2 nose_puidtiming_bdt_v2.root --h2 backg_jets_time_moments_0 --l2 'PU jets'  --ty 'event fraction' --tx '#mu = #Sigma E_{i} t_{i} / E_{jet} (ns)' --cap_in ' HF-Nose , (timing) ,' --cap_upr 'HF-Nose PhaseII Simulation' --out plots/weighted_mean_time --draw_opt 'hist' --xmin 0. --xmax 14. --norm  --rebin 1 ;

python var1D.py --f1 nose_puidtiming_bdt_v2.root  --h1 signal_jets_cumlong_fracs_2 --l1 'VBF jets' --f2 nose_puidtiming_bdt_v2.root --h2 backg_jets_cumlong_fracs_2 --l2 'PU jets'  --ty 'event fraction' --tx 'E_{[1-2]}/E_{jet}' --cap_in ' HF-Nose , (longitudinal) ,' --cap_upr 'HF-Nose PhaseII Simulation' --out plots/long12 --draw_opt 'hist' --xmin 0. --xmax 0.6 --norm  --rebin 1 ;


python var1D.py --f1 ../files/plots_massreg/massreg_all_mse_dil4_all.root  --h1 hdreg_higgs_all_200.0_100000.0 --l1 'Higgs (MSE/all)' --f2 ../files/plots_massreg/massreg_all_hub_dil4_all.root --h2 hdreg_higgs_all_200.0_100000.0 --l2 'Higgs (HUB/all)'   --f3 ../files/plots_massreg/massreg_higgsonly_mse_dil4_higgsonly.root --h3 hdreg_higgs_all_200.0_100000.0 --l3 'Higgs (MSE/higgs)'   --f4 ../files/plots_massreg/massreg_higgsonly_hub_dil4_higgsonly.root --h4 hdreg_higgs_all_200.0_100000.0 --l4 'Higgs (HUB/higgs)'  --ty 'event fraction' --tx 'm_{reg} / m_{target}' --cap_in ' all flavours  ,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_higgs_all --draw_opt 'hist' --norm  --rebin 50 ;

python var1D.py --f1 ../files/plots_massreg/massreg_all_mse_dil4_all.root  --h1 hdreg_qcd_all_200.0_100000.0 --l1 'QCD (MSE/all)' --f2 ../files/plots_massreg/massreg_all_hub_dil4_all.root --h2 hdreg_qcd_all_200.0_100000.0 --l2 'QCD (HUB/all)'   --f3 ../files/plots_massreg/massreg_higgsonly_mse_dil4_qcd.root --h3 hdreg_qcd_all_200.0_100000.0 --l3 'QCD (MSE/qcd)'   --f4 ../files/plots_massreg/massreg_higgsonly_hub_dil4_qcd.root --h4 hdreg_qcd_all_200.0_100000.0 --l4 'QCD (HUB/qcd)'  --ty 'event fraction' --tx 'm_{reg} / m_{target}' --cap_in ' all flavours  ,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_qcd_all --draw_opt 'hist' --norm  --rebin 50 ;


python var1D.py --f1 ../files/plots_massreg/massreg_all_mse_dil4_all.root  --h1 hdreg_higgs_bb_200.0_100000.0 --l1 'Higgs (MSE/all)' --f2 ../files/plots_massreg/massreg_all_hub_dil4_all.root --h2 hdreg_higgs_cc_200.0_100000.0 --l2 'Higgs (HUB/all)'   --f3 ../files/plots_massreg/massreg_higgsonly_mse_dil4_higgsonly.root --h3 hdreg_higgs_cc_200.0_100000.0 --l3 'Higgs (MSE/higgs)'   --f4 ../files/plots_massreg/massreg_higgsonly_hub_dil4_higgsonly.root --h4 hdreg_higgs_cc_200.0_100000.0 --l4 'Higgs (HUB/higgs)'  --ty 'event fraction' --tx 'm_{reg} / m_{target}' --cap_in ' c (cc) jet ,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_higgs_cc --draw_opt 'hist' --norm  --rebin 50 ;


python var1D.py --f1 ../files/plots_massreg/massreg_all_mse_dil4_all.root  --h1 hdreg_qcd_cc_200.0_100000.0 --l1 'QCD (MSE/all)' --f2 ../files/plots_massreg/massreg_all_hub_dil4_all.root --h2 hdreg_qcd_cc_200.0_100000.0 --l2 'QCD (HUB/all)'   --f3 ../files/plots_massreg/massreg_higgsonly_mse_dil4_qcd.root --h3 hdreg_qcd_cc_200.0_100000.0 --l3 'QCD (MSE/qcd)'   --f4 ../files/plots_massreg/massreg_higgsonly_hub_dil4_qcd.root --h4 hdreg_qcd_cc_200.0_100000.0 --l4 'QCD (HUB/qcd)'  --ty 'event fraction' --tx 'm_{reg} / m_{target}' --cap_in ' c (cc) flavours  ,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_qcd_cc --draw_opt 'hist' --norm  --rebin 50 ;




python var1D.py --f1 ../files/plots_massreg/massreg_all_mse_dil4_all.root  --h1 hdreg_higgs_cc_200.0_300.0 --l1 'Higgs (MSE/all)' --f2 ../files/plots_massreg/massreg_all_hub_dil4_all.root --h2 hdreg_higgs_cc_200.0_300.0 --l2 'Higgs (HUB/all)'   --f3 ../files/plots_massreg/massreg_higgsonly_mse_dil4_higgsonly.root --h3 hdreg_higgs_cc_200.0_300.0 --l3 'Higgs (MSE/higgs)'   --f4 ../files/plots_massreg/massreg_higgsonly_hub_dil4_higgsonly.root --h4 hdreg_higgs_cc_200.0_300.0 --l4 'Higgs (HUB/higgs)'  --ty 'event fraction' --tx 'm_{reg} / m_{target}' --cap_in ' c (cc) jet , 200 < p_{T} < 300 ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_higgs_cc_200.0_300.0 --draw_opt 'hist' --norm  --rebin 50 ;


python var1D.py --f1 ../files/plots_massreg/massreg_all_mse_dil4_all.root  --h1 hdreg_qcd_cc_200.0_300.0 --l1 'QCD (MSE/all)' --f2 ../files/plots_massreg/massreg_all_hub_dil4_all.root --h2 hdreg_qcd_cc_200.0_300.0 --l2 'QCD (HUB/all)'   --f3 ../files/plots_massreg/massreg_higgsonly_mse_dil4_qcd.root --h3 hdreg_qcd_cc_200.0_300.0 --l3 'QCD (MSE/qcd)'   --f4 ../files/plots_massreg/massreg_higgsonly_hub_dil4_qcd.root --h4 hdreg_qcd_cc_200.0_300.0 --l4 'QCD (HUB/qcd)'  --ty 'event fraction' --tx 'm_{reg} / m_{target}' --cap_in ' c (cc) flavours  , 200 < p_{T} < 300 ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_qcd_cc_200.0_300.0 --draw_opt 'hist' --norm  --rebin 50 ;



python var1D.py --f1 ../files/plots_massreg/massreg_all_mse_dil4_all.root  --h1 hdreg_higgs_cc_300.0_500.0 --l1 'Higgs (MSE/all)' --f2 ../files/plots_massreg/massreg_all_hub_dil4_all.root --h2 hdreg_higgs_cc_300.0_500.0 --l2 'Higgs (HUB/all)'   --f3 ../files/plots_massreg/massreg_higgsonly_mse_dil4_higgsonly.root --h3 hdreg_higgs_cc_300.0_500.0 --l3 'Higgs (MSE/higgs)'   --f4 ../files/plots_massreg/massreg_higgsonly_hub_dil4_higgsonly.root --h4 hdreg_higgs_cc_300.0_500.0 --l4 'Higgs (HUB/higgs)'  --ty 'event fraction' --tx 'm_{reg} / m_{target}' --cap_in ' c (cc) jet , 300 < p_{T} < 500 ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_higgs_cc_300.0_500.0 --draw_opt 'hist' --norm  --rebin 50 ;


python var1D.py --f1 ../files/plots_massreg/massreg_all_mse_dil4_all.root  --h1 hdreg_qcd_cc_300.0_500.0 --l1 'QCD (MSE/all)' --f2 ../files/plots_massreg/massreg_all_hub_dil4_all.root --h2 hdreg_qcd_cc_300.0_500.0 --l2 'QCD (HUB/all)'   --f3 ../files/plots_massreg/massreg_higgsonly_mse_dil4_qcd.root --h3 hdreg_qcd_cc_300.0_500.0 --l3 'QCD (MSE/qcd)'   --f4 ../files/plots_massreg/massreg_higgsonly_hub_dil4_qcd.root --h4 hdreg_qcd_cc_300.0_500.0 --l4 'QCD (HUB/qcd)'  --ty 'event fraction' --tx 'm_{reg} / m_{target}' --cap_in ' c (cc) flavours  , 300 < p_{T} < 500 ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_qcd_cc_300.0_500.0 --draw_opt 'hist' --norm  --rebin 50 ;


python var1D.py --f1 ../files/plots_massreg/massreg_all_mse_dil4_all.root  --h1 hdreg_higgs_cc_500.0_1000.0 --l1 'Higgs (MSE/all)' --f2 ../files/plots_massreg/massreg_all_hub_dil4_all.root --h2 hdreg_higgs_cc_500.0_1000.0 --l2 'Higgs (HUB/all)'   --f3 ../files/plots_massreg/massreg_higgsonly_mse_dil4_higgsonly.root --h3 hdreg_higgs_cc_500.0_1000.0 --l3 'Higgs (MSE/higgs)'   --f4 ../files/plots_massreg/massreg_higgsonly_hub_dil4_higgsonly.root --h4 hdreg_higgs_cc_500.0_1000.0 --l4 'Higgs (HUB/higgs)'  --ty 'event fraction' --tx 'm_{reg} / m_{target}' --cap_in ' c (cc) jet , 500 < p_{T} < 1000 ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_higgs_cc_500.0_1000.0 --draw_opt 'hist' --norm  --rebin 50 ;


python var1D.py --f1 ../files/plots_massreg/massreg_all_mse_dil4_all.root  --h1 hdreg_qcd_cc_500.0_1000.0 --l1 'QCD (MSE/all)' --f2 ../files/plots_massreg/massreg_all_hub_dil4_all.root --h2 hdreg_qcd_cc_500.0_1000.0 --l2 'QCD (HUB/all)'   --f3 ../files/plots_massreg/massreg_higgsonly_mse_dil4_qcd.root --h3 hdreg_qcd_cc_500.0_1000.0 --l3 'QCD (MSE/qcd)'   --f4 ../files/plots_massreg/massreg_higgsonly_hub_dil4_qcd.root --h4 hdreg_qcd_cc_500.0_1000.0 --l4 'QCD (HUB/qcd)'  --ty 'event fraction' --tx 'm_{reg} / m_{target}' --cap_in ' c (cc) flavours  , 500 < p_{T} < 1000 ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_qcd_cc_500.0_1000.0 --draw_opt 'hist' --norm  --rebin 50 ;

python var1D.py --f1 ../files/plots_massreg/massreg_all_mse_dil4_all.root  --h1 hreg_qcd_cc_200.0_100000.0 --l1 'QCD (MSE/all)' --f2 ../files/plots_massreg/massreg_all_hub_dil4_all.root --h2 hreg_qcd_cc_200.0_100000.0 --l2 'QCD (HUB/all)'   --f3 ../files/plots_massreg/massreg_higgsonly_mse_dil4_qcd.root --h3 hreg_qcd_cc_200.0_100000.0 --l3 'QCD (MSE/qcd)'   --f4 ../files/plots_massreg/massreg_higgsonly_hub_dil4_qcd.root --h4 hreg_qcd_cc_200.0_100000.0 --l4 'QCD (HUB/qcd)'  --ty 'event fraction' --tx 'm_{reg}' --cap_in ' c / cc flavours  ,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_qcd_cc_spectrum --draw_opt 'hist' --norm  --rebin 100 ;


python var1D.py --f1 ../files/plots_massreg/massreg_all_mse_dil4_all.root  --h1 hdreg_higgs_all_200.0_100000.0 --l1 'Higgs (MSE/all)' --f2 ../files/plots_massreg/massreg_all_hub_dil4_all.root --h2 hdreg_higgs_all_200.0_100000.0 --l2 'Higgs (HUB/all)'   --f3 ../files/plots_massreg/massreg_higgsonly_mse_dil4_higgsonly.root --h3 hdreg_higgs_all_200.0_100000.0 --l3 'Higgs (MSE/higgs)'   --f4 ../files/plots_massreg/massreg_higgsonly_hub_dil4_higgsonly.root --h4 hdreg_higgs_all_200.0_100000.0 --l4 'Higgs (HUB/higgs)'  --ty 'event fraction' --tx 'm_{reg} / m_{target}' --cap_in ' all flavours  ,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_higgs_all_spikes --draw_opt 'hist' --norm  --rebin 0 ;


python var1D.py --f1 ../files/plots_massreg/massreg_all_mse_dil4_all.root  --h1 hdreg_qcd_all_200.0_100000.0 --l1 'QCD (MSE/all)' --f2 ../files/plots_massreg/massreg_all_hub_dil4_all.root --h2 hdreg_qcd_all_200.0_100000.0 --l2 'QCD (HUB/all)'   --f3 ../files/plots_massreg/massreg_higgsonly_mse_dil4_qcd.root --h3 hdreg_qcd_all_200.0_100000.0 --l3 'QCD (MSE/qcd)'   --f4 ../files/plots_massreg/massreg_higgsonly_hub_dil4_qcd.root --h4 hdreg_qcd_all_200.0_100000.0 --l4 'QCD (HUB/qcd)'  --ty 'event fraction' --tx 'm_{reg} / m_{target}' --cap_in ' all flavours  ,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_qcd_all_spikes --draw_opt 'hist' --norm  --rebin 0 ;

## new selection

python var1D.py --f1 ../files/plots_massreg/massreg_all_hub_dil4_all.root  --h1 hdreg_higgs_cc_300.0_500.0 --l1 'Higgs (Hub/all)' --f2 ../files/massreg_all_cc_sel0_hub_dil4_all.root --h2 hdreg_higgs_cc_300.0_500.0 --l2 'Higgs (HUB/all) (sel0)'   --f3 ../files/massreg_all_cc_sel1_hub_dil4_all.root --h3 hdreg_higgs_cc_300.0_500.0 --l3 'Higgs (HUB/all) (sel1)' --ty 'event fraction' --tx 'm_{reg} / m_{target}' --cap_in ' c (cc) jet , 300 < p_{T} < 500 ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_higgs_cc_300.0_500.0 --draw_opt 'hist' --norm  --rebin 50 ;


python var1D.py --f1 ../files/plots_massreg/massreg_all_hub_dil4_all.root  --h1 hdreg_qcd_cc_300.0_500.0 --l1 'QCD (Hub/all)' --f2 ../files/massreg_all_cc_sel0_hub_dil4_all.root --h2 hdreg_qcd_cc_300.0_500.0 --l2 'QCD (HUB/all) (sel0)'   --f3 ../files/massreg_all_cc_sel1_hub_dil4_all.root --h3 hdreg_qcd_cc_300.0_500.0 --l3 'QCD (HUB/all) (sel1)' --ty 'event fraction' --tx 'm_{reg} / m_{target}' --cap_in ' c (cc) jet , 300 < p_{T} < 500 ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_qcd_cc_300.0_500.0 --draw_opt 'hist' --norm  --rebin 50 ;


python var1D.py --f1 ../files/plots_massreg/massreg_all_hub_dil4_all.root  --h1 hdreg_higgs_all_300.0_500.0 --l1 'Higgs (Hub/all)' --f2 ../files/massreg_all_cc_sel0_hub_dil4_all.root --h2 hdreg_higgs_all_300.0_500.0 --l2 'Higgs (HUB/all) (sel0)'   --f3 ../files/massreg_all_cc_sel1_hub_dil4_all.root --h3 hdreg_higgs_all_300.0_500.0 --l3 'Higgs (HUB/all) (sel1)' --ty 'event fraction' --tx 'm_{reg} / m_{target}' --cap_in ' c (cc) jet , 300 < p_{T} < 500 ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_higgs_all_300.0_500.0 --draw_opt 'hist' --norm  --rebin 50 ;


python var1D.py --f1 ../files/plots_massreg/massreg_all_hub_dil4_all.root  --h1 hdreg_qcd_all_300.0_500.0 --l1 'QCD (Hub/all)' --f2 ../files/massreg_all_cc_sel0_hub_dil4_all.root --h2 hdreg_qcd_all_300.0_500.0 --l2 'QCD (HUB/all) (sel0)'   --f3 ../files/massreg_all_cc_sel1_hub_dil4_all.root --h3 hdreg_qcd_all_300.0_500.0 --l3 'QCD (HUB/all) (sel1)' --ty 'event fraction' --tx 'm_{reg} / m_{target}' --cap_in ' c (cc) jet , 300 < p_{T} < 500 ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_qcd_all_300.0_500.0 --draw_opt 'hist' --norm  --rebin 50 ;



python var1D.py --f1 ../files/massreg_all_hub_dil4_all_msd_gt_20.root  --h1 hdreg_qcd_all_200.0_100000.0 --l1 'QCD  m_{SD} > 20 GeV' --f2 ../files/massreg_all_hub_dil4_all_msd_lt_20.root --h2 hdreg_qcd_all_200.0_100000.0 --l2 'QCD  m_{SD} < 20 GeV' --ty 'event fraction' --tx 'm_{reg} / m_{target}' --cap_in '  ,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_msd_gt --draw_opt 'hist' --norm  --rebin 50 ;

#### new plots with masscut

### higgs vs QCD inclusive comparison
python var1D.py --f1 ../files/massreg_all_hub_dil4_train_all_nomasscut.root  --h1 hdreg_higgs_all_200.0_100000.0 --l1 'Higgs (reg)' --f2 ../files/massreg_all_hub_dil4_train_all_nomasscut.root --h2 hdsd_higgs_all_200.0_100000.0 --l2 'Higgs (SD)' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in ' all flavours  ,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_higgs_all --draw_opt 'hist' --norm  --rebin 50 ;
python var1D.py --f1 ../files/massreg_all_hub_dil4_train_all_nomasscut.root  --h1 hdreg_qcd_all_200.0_100000.0 --l1 'QCD (reg)' --f2 ../files/massreg_all_hub_dil4_train_all_nomasscut.root --h2 hdsd_qcd_all_200.0_100000.0 --l2 'Higgs (SD)' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in ' all flavours  ,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_qcd_all --draw_opt 'hist' --norm  --rebin 50 ;

### sculpting
python var1D.py --f1 ../files/massreg_all_hub_dil4_train_all_nomasscut.root  --h1 hreg_qcd_all_200.0_100000.0 --l1 'QCD (reg)' --f2 ../files/massreg_all_hub_dil4_train_all_nomasscut.root --h2 hsd_qcd_all_200.0_100000.0 --l2 'QCD (SD)' --ty 'event fraction' --tx 'm_{reco}' --cap_in ' all flavours  ,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_qcd_sculpting_all --draw_opt 'hist' --norm  --rebin 50 --log ;
python var1D.py --f1 ../files/massreg_all_hub_dil4_train_all_nomasscut.root  --h1 hreg_qcd_cc_300.0_500.0 --l1 'QCD-cc (reg) [300,500]' --f2 ../files/massreg_all_hub_dil4_train_all_nomasscut.root --h2 hsd_qcd_cc_300.0_500.0 --l2 'QCD-cc (sd) [300,500]' --ty 'event fraction' --tx 'm_{reco}' --cap_in ' cc flavour  ,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_qcd_sculpting_cc_300_500 --draw_opt 'hist' --norm  --rebin 50 --log ;


### flavour comparison
python var1D.py --f1 ../files/massreg_all_hub_dil4_train_all_nomasscut.root  --h1 hdreg_higgs_qq_200.0_100000.0 --l1 'Higgs (qq)' --f2 ../files/massreg_all_hub_dil4_train_all_nomasscut.root --h2 hdreg_higgs_cc_200.0_100000.0 --l2 'Higgs (cc)'  --f3 ../files/massreg_all_hub_dil4_train_all_nomasscut.root --h3 hdreg_higgs_bb_200.0_100000.0 --l3 'Higgs (bb)' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in ' all flavours  ,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_higgs_flavours --draw_opt 'hist' --norm  --rebin 50 ;

python var1D.py --f1 ../files/massreg_all_hub_dil4_train_all_nomasscut.root  --h1 hdreg_qcd_qq_200.0_100000.0 --l1 'QCD (qq)' --f2 ../files/massreg_all_hub_dil4_train_all_nomasscut.root --h2 hdreg_qcd_cc_200.0_100000.0 --l2 'QCD (cc)'  --f3 ../files/massreg_all_hub_dil4_train_all_nomasscut.root --h3 hdreg_qcd_bb_200.0_100000.0 --l3 'QCD (bb)' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in ' all flavours  ,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_qcd_flavours --draw_opt 'hist' --norm  --rebin 50 ;

### pt comparison (only cc)
python var1D.py --f1 ../files/massreg_all_hub_dil4_train_all_nomasscut.root  --h1 hdreg_qcd_cc_200.0_300.0 --l1 'QCD (cc) [200,300]' --f2 ../files/massreg_all_hub_dil4_train_all_nomasscut.root  --h2 hdreg_qcd_cc_300.0_500.0 --l2 'QCD (cc) [300,500]' --f3 ../files/massreg_all_hub_dil4_train_all_nomasscut.root  --h3 hdreg_qcd_cc_500.0_1000.0 --l3 'QCD (cc) [500,1000]' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in ' ,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_qcd_pt --draw_opt 'hist' --norm  --rebin 100 ;

python var1D.py --f1 ../files/massreg_all_hub_dil4_train_all_nomasscut.root  --h1 hdreg_higgs_cc_200.0_300.0 --l1 'Higgs (cc) [200,300]' --f2 ../files/massreg_all_hub_dil4_train_all_nomasscut.root  --h2 hdreg_higgs_cc_300.0_500.0 --l2 'Higgs (cc) [300,500]' --f3 ../files/massreg_all_hub_dil4_train_all_nomasscut.root  --h3 hdreg_higgs_cc_500.0_1000.0 --l3 'Higgs (cc) [500,1000]' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in ' ,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_higgs_pt --draw_opt 'hist' --norm  --rebin 100 ;




## pt comparison each

python var1D.py --f1 ../files/massreg_all_hub_dil1_nomasscut_ptcut_ccsel1_train_all_nomasscut_ptcut_ccsel1.root  --h1 hdreg_higgs_cc_pt200.0_300.0_m100.0_150.0 --l1 'Higgs (cc) [200,300]' --f2 ../files/massreg_all_hub_dil1_nomasscut_ptcut_ccsel1_train_all_nomasscut_ptcut_ccsel1.root  --h2 hdreg_higgs_cc_pt300.0_500.0_m100.0_150.0 --l2 'Higgs (cc) [300,500]' --f3 ../files/massreg_all_hub_dil1_nomasscut_ptcut_ccsel1_train_all_nomasscut_ptcut_ccsel1.root  --h3 hdreg_higgs_cc_pt500.0_1000.0_m100.0_150.0 --l3 'Higgs (cc) [500,1000]' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in ' ,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_higgs_pt_ptcut_ccsel1 --draw_opt 'hist' --norm  --rebin 100 ;

python var1D.py --f1 ../files/massreg_all_hub_dil1_nomasscut_ccsel1_train_all_nomasscut_ccsel1.root  --h1 hdreg_higgs_cc_pt200.0_300.0_m100.0_150.0 --l1 'Higgs (cc) [200,300]' --f2 ../files/massreg_all_hub_dil1_nomasscut_ccsel1_train_all_nomasscut_ccsel1.root  --h2 hdreg_higgs_cc_pt300.0_500.0_m100.0_150.0 --l2 'Higgs (cc) [300,500]' --f3 ../files/massreg_all_hub_dil1_nomasscut_ccsel1_train_all_nomasscut_ccsel1.root  --h3 hdreg_higgs_cc_pt500.0_1000.0_m100.0_150.0 --l3 'Higgs (cc) [500,1000]' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in ' ,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_higgs_pt_ccsel1 --draw_opt 'hist' --norm  --rebin 100 ;

python var1D.py --f1 ../files/massreg_all_hub_dil1_nomasscut_bbccsel1_train_all_nomasscut_bbccsel1.root  --h1 hdreg_higgs_cc_pt200.0_300.0_m100.0_150.0 --l1 'Higgs (cc) [200,300]' --f2 ../files/massreg_all_hub_dil1_nomasscut_bbccsel1_train_all_nomasscut_bbccsel1.root  --h2 hdreg_higgs_cc_pt300.0_500.0_m100.0_150.0 --l2 'Higgs (cc) [300,500]' --f3 ../files/massreg_all_hub_dil1_nomasscut_bbccsel1_train_all_nomasscut_bbccsel1.root  --h3 hdreg_higgs_cc_pt500.0_1000.0_m100.0_150.0 --l3 'Higgs (cc) [500,1000]' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in ' ,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_higgs_pt_bbccsel1 --draw_opt 'hist' --norm  --rebin 100 ;


## low pt bin
python var1D.py --f1 ../files/massreg_all_hub_dil1_nomasscut_ptcut_ccsel1_train_all_nomasscut_ptcut_ccsel1.root  --h1 hdreg_higgs_cc_pt200.0_300.0_m100.0_150.0 --l1 'Higgs (cc) [200,300]' --f2 ../files/massreg_all_hub_dil1_nomasscut_ccsel1_train_all_nomasscut_ccsel1.root  --h2 hdreg_higgs_cc_pt200.0_300.0_m100.0_150.0 --l2 'Higgs (cc) [200,300]' --f3 ../files/massreg_all_hub_dil1_nomasscut_bbccsel1_train_all_nomasscut_bbccsel1.root  --h3 hdreg_higgs_cc_pt200.0_300.0_m100.0_150.0 --l3 'Higgs (cc) [200,300]' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in ' ,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_higgs_pt200_300 --draw_opt 'hist' --norm  --rebin 100 ;





### generic regression v1

## H->cc
python var1D.py --f1 ../files/massreg_all_hub_dil1_nomasscut_bbccsel1_train_all_nomasscut_ccsel1.root  --h1 hdreg_higgs_cc_pt200.0_300.0_m100.0_150.0 --l1 'H -> cc (reg.)' --f2 ../files/massreg_all_hub_dil1_nomasscut_bbccsel1_train_all_nomasscut_ccsel1.root --h2 hdsd_higgs_cc_pt200.0_300.0_m100.0_150.0 --l2 'H -> cc (SD)' --ty 'event fraction' --tx 'm_{reg} / m_{target}' --cap_in '     200 < p_{T} < 300 GeV,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_higgs_cc_200.0_300.0_gen --draw_opt 'hist' --norm  --rebin 100 ;

## H->bb
python var1D.py --f1 ../files/massreg_all_hub_dil1_nomasscut_bbccsel1_train_all_nomasscut_ccsel1.root  --h1 hdreg_higgs_bb_pt200.0_300.0_m100.0_150.0 --l1 'H -> bb (reg.)' --f2 ../files/massreg_all_hub_dil1_nomasscut_bbccsel1_train_all_nomasscut_ccsel1.root --h2 hdsd_higgs_bb_pt200.0_300.0_m100.0_150.0 --l2 'H -> bb (SD)' --ty 'event fraction' --tx 'm_{reg} / m_{target}' --cap_in '     200 < p_{T} < 300 GeV,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_higgs_bb_200.0_300.0_gen --draw_opt 'hist' --norm  --rebin 100 ;




## pt comp H->cc
python var1D.py --f1 ../files/massreg_all_hub_dil1_nomasscut_bbccsel1_train_all_nomasscut_ccsel1.root  --h1 hdreg_higgs_cc_pt200.0_300.0_m100.0_150.0 --l1 'Higgs (cc) [200,300]' --f2 ../files/massreg_all_hub_dil1_nomasscut_bbccsel1_train_all_nomasscut_ccsel1.root  --h2 hdreg_higgs_cc_pt300.0_500.0_m100.0_150.0 --l2 'Higgs (cc) [300,500]' --f3 ../files/massreg_all_hub_dil1_nomasscut_bbccsel1_train_all_nomasscut_ccsel1.root  --h3 hdreg_higgs_cc_pt500.0_1000.0_m100.0_150.0 --l3 'Higgs (cc) [500,1000]' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in ' p_{T} comparison,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_higgs_cc_pt_gen --draw_opt 'hist' --norm  --rebin 100 ;


## pt comp H->bb
python var1D.py --f1 ../files/massreg_all_hub_dil1_nomasscut_bbccsel1_train_all_nomasscut_ccsel1.root  --h1 hdreg_higgs_bb_pt200.0_300.0_m100.0_150.0 --l1 'Higgs (bb) [200,300]' --f2 ../files/massreg_all_hub_dil1_nomasscut_bbccsel1_train_all_nomasscut_ccsel1.root  --h2 hdreg_higgs_bb_pt300.0_500.0_m100.0_150.0 --l2 'Higgs (bb) [300,500]' --f3 ../files/massreg_all_hub_dil1_nomasscut_bbccsel1_train_all_nomasscut_ccsel1.root  --h3 hdreg_higgs_bb_pt500.0_1000.0_m100.0_150.0 --l3 'Higgs (bb) [500,1000]' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in ' p_{T} comparison,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_higgs_bb_pt_gen --draw_opt 'hist' --norm  --rebin 100 ;





## sculpting QCD
python var1D.py --f1  ../files/massreg_all_hub_dil1_nomasscut_bbccsel1_train_all_nomasscut_ccsel1.root --h1 hreg_qcd_all_pt200.0_300.0_m0.0_1000.0 --l1 'QCD (reg)' --f2 ../files/massreg_all_hub_dil1_nomasscut_bbccsel1_train_all_nomasscut_ccsel1.root --h2 hsd_qcd_all_pt200.0_300.0_m0.0_1000.0 --l2 'QCD (SD)' --ty 'event fraction' --tx 'm_{reco}' --cap_in ' all flavours  ,      200 < p_{T} < 300 GeV ,' --cap_upr 'CMS Simulation' --out plots/massreg_qcd_sculpting_all_200.0_300.0_gen --draw_opt 'hist' --norm  --rebin 50 --log ;


python var1D.py --f1  ../files/massreg_all_hub_dil1_nomasscut_bbccsel1_train_all_nomasscut_ccsel1.root --h1 hreg_qcd_all_pt300.0_500.0_m0.0_1000.0 --l1 'QCD (reg)' --f2 ../files/massreg_all_hub_dil1_nomasscut_bbccsel1_train_all_nomasscut_ccsel1.root --h2 hsd_qcd_all_pt300.0_500.0_m0.0_1000.0 --l2 'QCD (SD)' --ty 'event fraction' --tx 'm_{reco}' --cap_in ' all flavours  ,      300 < p_{T} < 500 GeV ,' --cap_upr 'CMS Simulation' --out plots/massreg_qcd_sculpting_all_300.0_500.0_gen --draw_opt 'hist' --norm  --rebin 50 --log ;

python var1D.py --f1  ../files/massreg_all_hub_dil1_nomasscut_bbccsel1_train_all_nomasscut_ccsel1.root --h1 hreg_qcd_all_pt500.0_1000.0_m0.0_1000.0 --l1 'QCD (reg)' --f2 ../files/massreg_all_hub_dil1_nomasscut_bbccsel1_train_all_nomasscut_ccsel1.root --h2 hsd_qcd_all_pt500.0_1000.0_m0.0_1000.0 --l2 'QCD (SD)' --ty 'event fraction' --tx 'm_{reco}' --cap_in ' all flavours  ,      500 < p_{T} < 1000 GeV ,' --cap_upr 'CMS Simulation' --out plots/massreg_qcd_sculpting_all_500.0_1000.0_gen --draw_opt 'hist' --norm  --rebin 50 --log ;






############################################################################
### Huilin version with weaver for AK15
############################################################################


#FILE="../files/massreg_weaver_huilin_median.root"
#FILE="../files/massreg_weaver_ak15_v3.root"
#FILE="../files/massreg_weaver_ak8.root"
#FILE="../files/massreg_weaver_huilin_ak8_large.root"
FILE="../files/massreg_weaver_huilin_ak15_large.root"



# H->cc low pT comparison with SD
python var1D.py --f1 ${FILE}  --h1 hdreg_higgs_cc_pt200.0_250.0_m100.0_150.0 --l1 'H -> cc (reg.)' --f2 ${FILE} --h2 hdsd_higgs_cc_pt200.0_250.0_m100.0_150.0 --l2 'H -> cc (SD)' --ty 'event fraction' --tx 'm_{reg} / m_{target}' --cap_in '     200 < p_{T} < 250 GeV,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_higgs_cc_200.0_250.0_gen --draw_opt 'hist' --norm  --rebin 100 ;

## H->bb low pT comparison with SD
python var1D.py --f1 ${FILE}  --h1 hdreg_higgs_bb_pt200.0_250.0_m100.0_150.0 --l1 'H -> bb (reg.)' --f2 ${FILE} --h2 hdsd_higgs_bb_pt250.0_300.0_m100.0_150.0 --l2 'H -> bb (SD)' --ty 'event fraction' --tx 'm_{reg} / m_{target}' --cap_in '     200 < p_{T} < 250 GeV,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_higgs_bb_250.0_300.0_gen --draw_opt 'hist' --norm  --rebin 100 ;

# H->cc all pT comparison with SD
python var1D.py --f1 ${FILE}  --h1 hdreg_higgs_cc_pt200.0_100000.0_m100.0_150.0 --l1 'H -> cc (reg.)' --f2 ${FILE} --h2 hdsd_higgs_cc_pt200.0_100000.0_m100.0_150.0 --l2 'H -> cc (SD)' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in '        200 < p_{T} < 500 GeV,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_higgs_cc_200.0_100000.0_gen --draw_opt 'hist' --norm  --rebin 100 --png;

# QCD all pT comparison with SD
python var1D.py --f1 ${FILE}  --h1 hdreg_qcd_cc_pt200.0_100000.0_m100.0_150.0 --l1 'QCD (reg.)' --f2 ${FILE} --h2 hdsd_qcd_cc_pt200.0_100000.0_m100.0_150.0 --l2 'QCD (SD)' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in '        200 < p_{T} < 500 GeV,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_qcd_cc_200.0_100000.0_gen --draw_opt 'hist' --norm  --rebin 100 --png ;

# H->bb all pT comparison with SD
python var1D.py --f1 ${FILE}  --h1 hdreg_higgs_bb_pt200.0_100000.0_m100.0_150.0 --l1 'H -> bb (reg.)' --f2 ${FILE} --h2 hdsd_higgs_bb_pt200.0_100000.0_m100.0_150.0 --l2 'H -> bb (SD)' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in '        200 < p_{T} < 500 GeV,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_higgs_bb_200.0_100000.0_gen --draw_opt 'hist' --norm  --rebin 100 --png ;
# H->qq all pT comparison with SD
python var1D.py --f1 ${FILE}  --h1 hdreg_higgs_qq_pt200.0_100000.0_m100.0_150.0 --l1 'H -> qq (reg.)' --f2 ${FILE} --h2 hdsd_higgs_qq_pt200.0_100000.0_m100.0_150.0 --l2 'H -> qq (SD)' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in '        200 < p_{T} < 500 GeV,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_higgs_qq_200.0_100000.0_gen --draw_opt 'hist' --norm  --rebin 100 --png ;


# flavour comparison all pTs
python var1D.py --f1 ${FILE}  --h1 hdreg_higgs_qq_pt200.0_100000.0_m100.0_150.0 --l1 'Higgs (qq)' --f2 ${FILE} --h2 hdreg_higgs_cc_pt200.0_100000.0_m100.0_150.0 --l2 'Higgs (cc)'  --f3 ${FILE} --h3 hdreg_higgs_bb_pt200.0_100000.0_m100.0_150.0 --l3 'Higgs (bb)' --ty 'event fraction' --tx 'm_{regression} / m_{target}' --cap_in '      200 < p_{T} < 500 GeV ,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_higgs_flavours --draw_opt 'hist' --norm  --rebin 100 ;
python var1D.py --f1 ${FILE}  --h1 hdreg_qcd_qq_pt200.0_100000.0_m100.0_150.0 --l1 'QCD (qq)' --f2 ${FILE} --h2 hdreg_qcd_cc_pt200.0_100000.0_m100.0_150.0 --l2 'QCD (cc)'  --f3 ${FILE} --h3 hdreg_qcd_bb_pt200.0_100000.0_m100.0_150.0 --l3 'QCD (bb)' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in ' all flavours  ,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_qcd_flavours --draw_opt 'hist' --norm  --rebin 100 ;

# pt comp H->cc
python var1D.py --f1 ${FILE}  --h1 hdreg_higgs_cc_pt200.0_250.0_m100.0_150.0 --l1 '200 < p_{T} < 250' --f2 ${FILE}  --h2 hdreg_higgs_cc_pt250.0_300.0_m100.0_150.0 --l2 '250 < p_{T} < 300'   --f3 ${FILE}  --h3 hdreg_higgs_cc_pt300.0_400.0_m100.0_150.0 --l3 '300 < p_{T} < 400'  --f4 ${FILE}  --h4 hdreg_higgs_cc_pt400.0_500.0_m100.0_150.0 --l4 '400 < p_{T} < 500' --ty 'event fraction' --tx 'M_{reg} / M_{target}' --cap_in '    mass regression,  H #rightarrow cc ,' --cap_upr 'CMS Simulation' --out plots/massreg_higgs_cc_pt_gen --draw_opt 'hist' --norm  --rebin 100 --overflow;

python var1D.py --f1 ${FILE}  --h1 hdsd_higgs_cc_pt200.0_250.0_m100.0_150.0 --l1 '200 < p_{T} < 250' --f2 ${FILE}  --h2 hdsd_higgs_cc_pt250.0_300.0_m100.0_150.0 --l2 '250 < p_{T} < 300'   --f3 ${FILE}  --h3 hdsd_higgs_cc_pt300.0_400.0_m100.0_150.0 --l3 '300 < p_{T} < 400'  --f4 ${FILE}  --h4 hdsd_higgs_cc_pt400.0_500.0_m100.0_150.0 --l4 '400 < p_{T} < 500' --ty 'event fraction' --tx 'M_{SD} / M_{target}' --cap_in '    soft drop mass, H #rightarrow cc  ,' --cap_upr 'CMS Simulation' --out plots/masssd_higgs_cc_pt_gen --draw_opt 'hist' --norm  --rebin 100 --overflow ;

python var1D.py --f1 ${FILE}  --h1 hdreg_qcd_cc_pt200.0_250.0_m100.0_150.0 --l1 '200 < p_{T} < 250' --f2 ${FILE}  --h2 hdreg_qcd_cc_pt250.0_300.0_m100.0_150.0 --l2 '250 < p_{T} < 300'   --f3 ${FILE}  --h3 hdreg_qcd_cc_pt300.0_400.0_m100.0_150.0 --l3 '300 < p_{T} < 400'  --f4 ${FILE}  --h4 hdreg_qcd_cc_pt400.0_500.0_m100.0_150.0 --l4 '400 < p_{T} < 500' --ty 'event fraction' --tx 'M_{reg} / M_{target}' --cap_in '    mass regression,   QCD (c/cc),' --cap_upr 'CMS Simulation' --out plots/massreg_qcd_cc_pt_gen --draw_opt 'hist' --norm  --rebin 100 --overflow;

python var1D.py --f1 ${FILE}  --h1 hdsd_qcd_cc_pt200.0_250.0_m100.0_150.0 --l1 '200 < p_{T} < 250' --f2 ${FILE}  --h2 hdsd_qcd_cc_pt250.0_300.0_m100.0_150.0 --l2 '250 < p_{T} < 300'   --f3 ${FILE}  --h3 hdsd_qcd_cc_pt300.0_400.0_m100.0_150.0 --l3 '300 < p_{T} < 400'  --f4 ${FILE}  --h4 hdsd_qcd_cc_pt400.0_500.0_m100.0_150.0 --l4 '400 < p_{T} < 500' --ty 'event fraction' --tx 'M_{SD} / M_{target}' --cap_in '    soft drop mass,   QCD (c/cc)  ,' --cap_upr 'CMS Simulation' --out plots/masssd_qcd_cc_pt_gen --draw_opt 'hist' --norm  --rebin 100 --overflow ;



## pt comp H->bb
python var1D.py --f1 ${FILE}  --h1 hdreg_higgs_bb_pt200.0_100000.0_m100.0_150.0 --l1 'Higgs (bb) [200,500]' --f2 ${FILE}  --h2 hdreg_higgs_bb_pt200.0_100000.0_m100.0_150.0 --l2 'Higgs (bb) [200,500]' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in ' p_{T} comparison,  ,' --cap_upr 'CMS Simulation' --out plots/massreg_higgs_bb_pt_gen --draw_opt 'hist' --norm  --rebin 100 ;


# sculpting QCD
python var1D.py --f1  ${FILE} --h1 hreg_qcd_all_pt200.0_100000.0_m0.0_1000.0 --l1 'QCD (reg)' --f2 ${FILE} --h2 hsd_qcd_all_pt200.0_100000.0_m0.0_1000.0 --l2 'QCD (SD)' --ty 'event fraction' --tx 'm_{reco}' --cap_in ' all flavours  ,       p_{T} > 200 GeV,' --cap_upr 'CMS Simulation' --out plots/massreg_qcd_sculpting_all_200.0_10000.0_gen --draw_opt 'hist' --norm  --rebin 50 --log ;


## resolution and efficiency plots vs pT
filename=$(basename -- "${FILE}")
extension="${filename##*.}"
filename="${filename%.*}"
echo ${filename}

python massreg/resolution.py ${FILE} ${filename}



############################################################################
### Huilin version with weaver for AK8 (H->bb)
############################################################################


FILE="../files/massreg_weaver_huilin_ak8_large.root"
#FILE="../files/massreg_weaver_huilin_ak15_large.root"


# flavour comparison all pTs
python var1D.py --f1 ${FILE}  --h1 hdreg_higgs_qq_pt200.0_100000.0_m100.0_150.0 --l1 'Higgs (qq)' --f2 ${FILE} --h2 hdreg_higgs_cc_pt200.0_100000.0_m100.0_150.0 --l2 'Higgs (cc)'  --f3 ${FILE} --h3 hdreg_higgs_bb_pt200.0_100000.0_m100.0_150.0 --l3 'Higgs (bb)' --ty 'event fraction' --tx 'm_{regression} / m_{target}' --cap_in '  AK8 jets,       p_{T} > 200 GeV ,' --cap_upr 'CMS Simulation' --out plots/massreg_higgs_flavours --draw_opt 'hist' --norm  --rebin 100 --png ;
python var1D.py --f1 ${FILE}  --h1 hdreg_qcd_qq_pt200.0_100000.0_m100.0_150.0 --l1 'QCD (q/qq)' --f2 ${FILE} --h2 hdreg_qcd_cc_pt200.0_100000.0_m100.0_150.0 --l2 'QCD (c/cc)'  --f3 ${FILE} --h3 hdreg_qcd_bb_pt200.0_100000.0_m100.0_150.0 --l3 'QCD (b/bb)' --ty 'event fraction' --tx 'm_{regression} / m_{target}' --cap_in '  AK8 jets,       p_{T} > 200 GeV ,' --cap_upr 'CMS Simulation' --out plots/massreg_qcd_flavours --draw_opt 'hist' --norm  --rebin 100 --png ;

# H->bb all pT comparison with SD
python var1D.py --f1 ${FILE}  --h1 hdreg_higgs_bb_pt200.0_100000.0_m100.0_150.0 --l1 'H -> bb (reg.)' --f2 ${FILE} --h2 hdsd_higgs_bb_pt200.0_100000.0_m100.0_150.0 --l2 'H -> bb (SD)' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in '  AK8 jets,       p_{T} > 200 GeV ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_higgs_bb_200.0_100000.0_gen --draw_opt 'hist' --norm  --rebin 100 --png ;

# H->cc all pT comparison with SD
python var1D.py --f1 ${FILE}  --h1 hdreg_higgs_cc_pt200.0_100000.0_m100.0_150.0 --l1 'H -> cc (reg.)' --f2 ${FILE} --h2 hdsd_higgs_cc_pt200.0_100000.0_m100.0_150.0 --l2 'H -> cc (SD)' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in '  AK8 jets,       p_{T} > 200 GeV ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_higgs_cc_200.0_100000.0_gen --draw_opt 'hist' --norm  --rebin 100 --png ;
# H->qq all pT comparison with SD
python var1D.py --f1 ${FILE}  --h1 hdreg_higgs_qq_pt200.0_100000.0_m100.0_150.0 --l1 'H -> qq (reg.)' --f2 ${FILE} --h2 hdsd_higgs_qq_pt200.0_100000.0_m100.0_150.0 --l2 'H -> qq (SD)' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in '  AK8 jets,       p_{T} > 200 GeV ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_higgs_qq_200.0_100000.0_gen --draw_opt 'hist' --norm  --rebin 100 --png ;

# QCD all pT comparison with SD
python var1D.py --f1 ${FILE}  --h1 hdreg_qcd_bb_pt200.0_100000.0_m100.0_150.0 --l1 'QCD (reg.)' --f2 ${FILE} --h2 hdsd_qcd_bb_pt200.0_100000.0_m100.0_150.0 --l2 'QCD (SD)' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in '  AK8 jets,       p_{T} > 200 GeV ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_qcd_bb_200.0_100000.0_gen --draw_opt 'hist' --norm  --rebin 100 --png ;

# pt comp H->bb
python var1D.py --f1 ${FILE}  --h1 hdreg_higgs_bb_pt250.0_300.0_m100.0_150.0 --l1 '250 < p_{T} < 300'   --f2 ${FILE}  --h2 hdreg_higgs_bb_pt300.0_400.0_m100.0_150.0 --l2 '300 < p_{T} < 400'  --f3 ${FILE}  --h3 hdreg_higgs_bb_pt400.0_500.0_m100.0_150.0 --l3 '400 < p_{T} < 500'  --f4 ${FILE}  --h4 hdreg_higgs_bb_pt500.0_750.0_m100.0_150.0 --l4 '500 < p_{T} < 750' --ty 'event fraction' --tx 'M_{reg} / M_{target}' --cap_in '  AK8 jets,    H #rightarrow bb,   mass regression' --cap_upr 'CMS Simulation' --out plots/massreg_higgs_bb_pt_gen --draw_opt 'hist' --norm  --rebin 100 --overflow --png ;

python var1D.py --f1 ${FILE}  --h1 hdsd_higgs_bb_pt250.0_300.0_m100.0_150.0 --l1 '250 < p_{T} < 300'   --f2 ${FILE}  --h2 hdsd_higgs_bb_pt300.0_400.0_m100.0_150.0 --l2 '300 < p_{T} < 400'  --f3 ${FILE}  --h3 hdsd_higgs_bb_pt400.0_500.0_m100.0_150.0 --l3 '400 < p_{T} < 500'  --f4 ${FILE}  --h4 hdsd_higgs_bb_pt500.0_750.0_m100.0_150.0 --l4 '500 < p_{T} < 750' --ty 'event fraction' --tx 'M_{SD} / M_{target}' --cap_in '  AK8 jets,    H #rightarrow bb,   soft drop mass' --cap_upr 'CMS Simulation' --out plots/masssd_higgs_bb_pt_gen --draw_opt 'hist' --norm  --rebin 100 --overflow --png ;

python var1D.py --f1 ${FILE}  --h1 hdreg_qcd_bb_pt250.0_300.0_m100.0_150.0 --l1 '250 < p_{T} < 300'   --f2 ${FILE}  --h2 hdreg_qcd_bb_pt300.0_400.0_m100.0_150.0 --l2 '300 < p_{T} < 400'  --f3 ${FILE}  --h3 hdreg_qcd_bb_pt400.0_500.0_m100.0_150.0 --l3 '400 < p_{T} < 500'  --f4 ${FILE}  --h4 hdreg_qcd_bb_pt500.0_750.0_m100.0_150.0 --l4 '500 < p_{T} < 750' --ty 'event fraction' --tx 'M_{reg} / M_{target}' --cap_in '  AK8 jets,     QCD (b/bb),   mass regression' --cap_upr 'CMS Simulation' --out plots/massreg_qcd_bb_pt_gen --draw_opt 'hist' --norm  --rebin 100 --overflow --png ;

python var1D.py --f1 ${FILE}  --h1 hdsd_qcd_bb_pt250.0_300.0_m100.0_150.0 --l1 '250 < p_{T} < 300'   --f2 ${FILE}  --h2 hdsd_qcd_bb_pt300.0_400.0_m100.0_150.0 --l2 '300 < p_{T} < 400'  --f3 ${FILE}  --h3 hdsd_qcd_bb_pt400.0_500.0_m100.0_150.0 --l3 '400 < p_{T} < 500'  --f4 ${FILE}  --h4 hdsd_qcd_bb_pt500.0_750.0_m100.0_150.0 --l4 '500 < p_{T} < 750' --ty 'event fraction' --tx 'M_{SD} / M_{target}' --cap_in '  AK8 jets,     QCD (b/bb),   soft drop mass' --cap_upr 'CMS Simulation' --out plots/masssd_qcd_bb_pt_gen --draw_opt 'hist' --norm  --rebin 100 --overflow --png ;


# sculpting QCD
python var1D.py --f1  ${FILE} --h1 hreg_qcd_all_pt200.0_100000.0_m0.0_1000.0 --l1 'QCD (reg)' --f2 ${FILE} --h2 hsd_qcd_all_pt200.0_100000.0_m0.0_1000.0 --l2 'QCD (SD)' --ty 'event fraction' --tx 'm_{reco}' --cap_in ' all flavours  ,   p_{T} >  200 GeV ,' --cap_upr 'CMS Simulation' --out plots/massreg_qcd_sculpting_all_200.0_10000.0_gen --draw_opt 'hist' --norm  --rebin 50 --log --png ;



## resolution and efficiency plots vs pT
filename=$(basename -- "${FILE}")
extension="${filename##*.}"
filename="${filename%.*}"
echo ${filename}

python massreg/resolution.py ${FILE} ${filename}

### pu study

JET="ak15"
FS="cc"
PUFILE1="../files/massreg_weaver_huilin_${JET}_0_20_pu.root"
PUFILE2="../files/massreg_weaver_huilin_${JET}_20_40_pu.root"
PUFILE3="../files/massreg_weaver_huilin_${JET}_40_60_pu.root"

python var1D.py --f1 ${PUFILE1}  --h1 hdreg_higgs_${FS}_pt200.0_100000.0_m100.0_150.0 --l1 '0 < n_{PV} < 20'  --f2 ${PUFILE2}  --h2 hdreg_higgs_${FS}_pt200.0_100000.0_m100.0_150.0 --l2 '20 < n_{PV} < 40'  --f3 ${PUFILE3}  --h3 hdreg_higgs_${FS}_pt200.0_100000.0_m100.0_150.0 --l3 '40 < n_{PV} < 60' --ty 'event fraction' --tx 'M_{reg} / M_{target}' --cap_in ' '"${JET}"' jets,    H #rightarrow '"${FS}"',   mass regression' --cap_upr 'CMS Simulation' --out plots/massreg_higgs_${JET}_${FS}_pu --draw_opt 'hist' --norm  --rebin 50 --overflow --png ;

python var1D.py --f1 ${PUFILE1}  --h1 hdsd_higgs_${FS}_pt200.0_100000.0_m100.0_150.0 --l1 '0 < n_{PV} < 20'  --f2 ${PUFILE2}  --h2 hdsd_higgs_${FS}_pt200.0_100000.0_m100.0_150.0 --l2 '20 < n_{PV} < 40'  --f3 ${PUFILE3}  --h3 hdsd_higgs_${FS}_pt200.0_100000.0_m100.0_150.0 --l3 '40 < n_{PV} < 60' --ty 'event fraction' --tx 'M_{SD} / M_{target}' --cap_in ' '"${JET}"' jets,    H #rightarrow '"${FS}"',   mass regression' --cap_upr 'CMS Simulation' --out plots/masssd_higgs_${JET}_${FS}_pu --draw_opt 'hist' --norm  --rebin 50 --overflow --png ;


### validation
FILE="../files/validation.root"

python var1D.py --f1 ${FILE}  --h1 hmregLoose  --l1 'Loose' --f2 ${FILE}  --h2 hmregMedium  --l2 'Medium' --f3 ${FILE}  --h3 hmregTight  --l3 'Tight' --ty 'event fraction' --tx 'M_{reg}' --cap_in ' AK15 jets,    VH #rightarrow #nu #nu cc,   mass regression' --cap_upr 'CMS Simulation' --out plots/validation --draw_opt 'hist' --norm  --overflow --png ;
python var1D.py --f1 ${FILE}  --h1 hmregLoose_norm  --l1 'Loose' --f2 ${FILE}  --h2 hmregMedium_norm  --l2 'Medium' --f3 ${FILE}  --h3 hmregTight_norm  --l3 'Tight' --ty 'event fraction' --tx 'M_{reg} / M_{H}' --cap_in ' AK15 jets,    VH #rightarrow #nu #nu cc,   mass regression' --cap_upr 'CMS Simulation' --out plots/validation_norm --draw_opt 'hist' --norm  --overflow --png ;

python resolution_validation.py ../../files/validation.root

### validation ak8
FILE="../files/ak8_validation.root"
python var1D.py --f1 ${FILE}  --h1 hmregLoose_1  --l1 'Loose' --f2 ${FILE}  --h2 hmregMedium_1  --l2 'Medium' --f3 ${FILE}  --h3 hmregTight_1  --l3 'Tight' --ty 'event fraction' --tx 'M_{reg}' --cap_in ' VBF HH #rightarrow 4b, C_{2V} = 0,  leading AK8 jet  ' --cap_upr 'CMS Simulation' --out plots/ak8_1_validation --draw_opt 'hist' --norm  --overflow --png ;
python var1D.py --f1 ${FILE}  --h1 hmregLoose_2  --l1 'Loose' --f2 ${FILE}  --h2 hmregMedium_2  --l2 'Medium' --f3 ${FILE}  --h3 hmregTight_2  --l3 'Tight' --ty 'event fraction' --tx 'M_{reg}' --cap_in ' VBF HH #rightarrow 4b, C_{2V} = 0,  sub-leading AK8 jet  ' --cap_upr 'CMS Simulation' --out plots/ak8_2_validation --draw_opt 'hist' --norm  --overflow --png ;

python var1D.py --f1 ${FILE}  --h1 hmregLoose_1_norm  --l1 'Loose' --f2 ${FILE}  --h2 hmregMedium_1_norm  --l2 'Medium' --f3 ${FILE}  --h3 hmregTight_1_norm  --l3 'Tight' --ty 'event fraction' --tx 'M_{reg} / M_{H}' --cap_in ' VBF HH #rightarrow 4b, C_{2V} = 0,  leading AK8 jet  ' --cap_upr 'CMS Simulation' --out plots/ak8_1_validation_norm --draw_opt 'hist' --norm  --overflow --png ;
python var1D.py --f1 ${FILE}  --h1 hmregLoose_2_norm  --l1 'Loose' --f2 ${FILE}  --h2 hmregMedium_2_norm  --l2 'Medium' --f3 ${FILE}  --h3 hmregTight_2_norm  --l3 'Tight' --ty 'event fraction' --tx 'M_{reg} / M_{H}' --cap_in ' VBF HH #rightarrow 4b, C_{2V} = 0,  sub-leading AK8 jet  ' --cap_upr 'CMS Simulation' --out plots/ak8_2_validation_norm --draw_opt 'hist' --norm  --overflow --png ;


### compare H->bb and W->cs
python var1D.py --f1  "../files/ak8_validation.root" --h1 hmregLoose_2_norm  --l1 'H #rightarrow bb' --f2   "../files/ak8_validation_wcs.root" --h2 hmreg_wcs_norm  --l2 'W #rightarrow cs'  --ty 'event fraction' --tx 'M_{reg} / M' --cap_in '     p_{T} > 200 GeV, ,   ' --cap_upr 'CMS Simulation' --out plots/ak8_validation_h_vs_w --draw_opt 'hist' --norm  --overflow --png ;

### compare H->cc and W->cs
python var1D.py --f1  "../files/ak15_validation_hcc.root" --h1 hmreg_hcc_norm  --l1 'H #rightarrow cc' --f2   "../files/ak15_validation_wcs.root" --h2 hmreg_wcs_norm  --l2 'W #rightarrow cs'  --ty 'event fraction' --tx 'M_{reg} / M' --cap_in '     p_{T} > 200 GeV, ,   ' --cap_upr 'CMS Simulation' --out plots/ak8_validation_h_vs_w --draw_opt 'hist' --norm  --overflow --png ;



############################################################################
### Compare old training vs legacy training
############################################################################


FILE="../files/massreg_weaver_huilin_ak8_large.root"
FILE2="../files/massreg_weaver_huilin_ak8_large_v2.root"


# H->bb all pT regression compare old vs new
python var1D.py --f1 ${FILE}  --h1 hdreg_higgs_bb_pt200.0_100000.0_m100.0_150.0 --l1 'H -> bb (old)' --f2 ${FILE2} --h2 hdreg_higgs_bb_pt200.0_100000.0_m100.0_150.0 --l2 'H -> bb (legacy)' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in '  AK8 jets,       p_{T} > 200 GeV ,' --cap_upr 'CMS Simulation' --out plots/massreg_higgs_bb_200.0_100000.0_oldvsleg --draw_opt 'hist' --norm  --rebin 100 --png ;

# H->cc all pT regression compare old vs new
python var1D.py --f1 ${FILE}  --h1 hdreg_higgs_cc_pt200.0_100000.0_m100.0_150.0 --l1 'H -> cc (old)' --f2 ${FILE2} --h2 hdreg_higgs_cc_pt200.0_100000.0_m100.0_150.0 --l2 'H -> cc (legacy)' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in '  AK8 jets,       p_{T} > 200 GeV ,' --cap_upr 'CMS Simulation' --out plots/massreg_higgs_cc_200.0_100000.0_oldvsleg --draw_opt 'hist' --norm  --rebin 100 --png ;

# H->bb all pT softdrop  compare old vs new
python var1D.py --f1 ${FILE}  --h1 hdsd_higgs_bb_pt200.0_100000.0_m100.0_150.0 --l1 'H -> bb (old)' --f2 ${FILE2} --h2 hdsd_higgs_bb_pt200.0_100000.0_m100.0_150.0 --l2 'H -> bb (legacy)' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in '  AK8 jets,       p_{T} > 200 GeV ,' --cap_upr 'CMS Simulation' --out plots/sd_higgs_bb_200.0_100000.0_oldvsleg --draw_opt 'hist' --norm  --rebin 100 --png ;

# H->cc all pT softdrop  compare old vs new
python var1D.py --f1 ${FILE}  --h1 hdsd_higgs_cc_pt200.0_100000.0_m100.0_150.0 --l1 'H -> cc (old)' --f2 ${FILE2} --h2 hdsd_higgs_cc_pt200.0_100000.0_m100.0_150.0 --l2 'H -> cc (legacy)' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in '  AK8 jets,       p_{T} > 200 GeV ,' --cap_upr 'CMS Simulation' --out plots/sd_higgs_cc_200.0_100000.0_oldvsleg --draw_opt 'hist' --norm  --rebin 100 --png ;

# QCD (bb) all pT comparison with SD
python var1D.py --f1 ${FILE}  --h1 hdreg_qcd_bb_pt200.0_100000.0_m100.0_150.0 --l1 'QCD (old.)' --f2 ${FILE2} --h2 hdreg_qcd_bb_pt200.0_100000.0_m100.0_150.0 --l2 'QCD (legacy)' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in '  AK8 jets,       p_{T} > 200 GeV ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_qcd_bb_200.0_100000.0_oldvsleg --draw_opt 'hist' --norm  --rebin 100 --png ;

# QCD (cc) all pT comparison with SD
python var1D.py --f1 ${FILE}  --h1 hdreg_qcd_cc_pt200.0_100000.0_m100.0_150.0 --l1 'QCD (old.)' --f2 ${FILE2} --h2 hdreg_qcd_cc_pt200.0_100000.0_m100.0_150.0 --l2 'QCD (legacy)' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in '  AK8 jets,       p_{T} > 200 GeV ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_qcd_cc_200.0_100000.0_oldvsleg --draw_opt 'hist' --norm  --rebin 100 --png ;


# H->bb all pT comparison with SD
python var1D.py --f1 ${FILE2}  --h1 hdreg_higgs_bb_pt200.0_100000.0_m100.0_150.0 --l1 'H -> bb (reg.)' --f2 ${FILE2} --h2 hdsd_higgs_bb_pt200.0_100000.0_m100.0_150.0 --l2 'H -> bb (SD)' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in '  AK8 jets,       p_{T} > 200 GeV ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_higgs_bb_200.0_100000.0_gen --draw_opt 'hist' --norm  --rebin 100 --png ;

# H->cc all pT comparison with SD
python var1D.py --f1 ${FILE2}  --h1 hdreg_higgs_cc_pt200.0_100000.0_m100.0_150.0 --l1 'H -> cc (reg.)' --f2 ${FILE2} --h2 hdsd_higgs_cc_pt200.0_100000.0_m100.0_150.0 --l2 'H -> cc (SD)' --ty 'event fraction' --tx 'm_{reco} / m_{target}' --cap_in '  AK8 jets,       p_{T} > 200 GeV ,' --cap_upr 'CMS Simulation' --out plots/massreg_comp_higgs_cc_200.0_100000.0_gen --draw_opt 'hist' --norm  --rebin 100 --png ;



# pt comp H->bb
python var1D.py --f1 ${FILE2}  --h1 hdreg_higgs_bb_pt250.0_300.0_m100.0_150.0 --l1 '250 < p_{T} < 300'   --f2 ${FILE2}  --h2 hdreg_higgs_bb_pt300.0_400.0_m100.0_150.0 --l2 '300 < p_{T} < 400'  --f3 ${FILE2}  --h3 hdreg_higgs_bb_pt400.0_500.0_m100.0_150.0 --l3 '400 < p_{T} < 500'  --f4 ${FILE2}  --h4 hdreg_higgs_bb_pt500.0_750.0_m100.0_150.0 --l4 '500 < p_{T} < 750' --ty 'event fraction' --tx 'M_{reg} / M_{target}' --cap_in '  AK8 jets,    H #rightarrow bb,   mass regression' --cap_upr 'CMS Simulation' --out plots/massreg_higgs_bb_pt_gen --draw_opt 'hist' --norm  --rebin 100 --overflow --png ;


# pt comp H->cc
python var1D.py --f1 ${FILE2}  --h1 hdreg_higgs_cc_pt250.0_300.0_m100.0_150.0 --l1 '250 < p_{T} < 300'   --f2 ${FILE2}  --h2 hdreg_higgs_cc_pt300.0_400.0_m100.0_150.0 --l2 '300 < p_{T} < 400'  --f3 ${FILE2}  --h3 hdreg_higgs_cc_pt400.0_500.0_m100.0_150.0 --l3 '400 < p_{T} < 500'  --f4 ${FILE2}  --h4 hdreg_higgs_cc_pt500.0_750.0_m100.0_150.0 --l4 '500 < p_{T} < 750' --ty 'event fraction' --tx 'M_{reg} / M_{target}' --cap_in '  AK8 jets,    H #rightarrow cc,   mass regression' --cap_upr 'CMS Simulation' --out plots/massreg_higgs_cc_pt_gen --draw_opt 'hist' --norm  --rebin 100 --overflow --png ;


## resolution and efficiency plots vs pT
filename=$(basename -- "${FILE}")
extension="${filename##*.}"
filename="${filename%.*}"
echo ${filename}

python massreg/resolution.py ${FILE} ${filename}


## resolution and efficiency plots vs pT
filename=$(basename -- "${FILE2}")
extension="${filename##*.}"
filename="${filename%.*}"
echo ${filename}

python massreg/resolution.py ${FILE2} ${filename}
